### PR TITLE
add colorizeLogEntries hook to docs (de/en)

### LINKED ISSUE #196: Add the "colorizeLogEntries" hook
Chapter 7
From Contao 3.3.0
Reference: https://github.com/contao/core/commit/b505a7618d376cf310a5f4da47b55858eb6cf93d

### PR DESCRIPTION
**Pull request by bezin**
This fixes #196. Once again, may you please add a french translation @lionel-m :)

### CODE REVIEW

**Comment by aschempp** [comment]
The manual for Contao 3.3 is no longer maintained. I can manually cherry pick that, but in the future please only create PRs for Contao 3.2 or 3.4 (though their support will end soon too).

PS: also be aware that we started a new hooks documentatino some time ago at https://github.com/contao/docs/blob/master/api/hooks.md
After switching to GitBook now I want to create a new book for that. I would suggest to add new hooks there and no longer to the existing manual, but what do you two @bezin and @lionel-m think about that?

**Comment by bezin** [comment]
Ok, thanks for cherry-picking, I'll pay attention to that in the future. 
I can add the two hooks I documented to https://github.com/contao/docs/blob/master/api/hooks.md as well.  Would you like to drop the Hooks section in the manual completely?
I think it would be good to have the new book here https://docs.contao.org/en/ under developer documentation / API. Is that what you planned to do, @aschempp ?

**Comment by lionel-m** [comment]
@bezin : each validated PR will be translated into French :) Thanks for your contribution!

@aschempp : Yes I am in favour of removing the chapter "Hooks" for the benefit of a new API documentation.

**Comment by aschempp** [comment]
Merged in 57cd44e7649705e187b8a75de0e570d1a9c1b87b

I have also added a few minor improvements in 1c14356434e15fd6f95256e99a60ad947a8feb03

**Pull request closed without merging**
