### PR TITLE
C4 - remove outdated informations and features that are not ready yet.

### PR DESCRIPTION
**Pull request by lionel-m**
### Outdated informations
- The paragraph "[CSS classes of included elements](https://github.com/contao/core-bundle/blob/master/UPGRADE.md#css-classes-of-included-elements)" has been added to the style-sheets chapter.
- The old IE7 tip has been removed from the style-sheets chapter.
- The reference about [slimbox](https://github.com/contao/core-bundle/blob/master/UPGRADE.md#mootools-slimbox) has been removed.
- All references about the Safe Mode Hack have been removed.
- The [class names (CE + modules)](https://github.com/contao/core-bundle/blob/master/UPGRADE.md#template-name-changes) have been updated.
- The form field "[headline](https://github.com/contao/core-bundle/blob/master/UPGRADE.md#form-field-headline)" has been removed.
- The reference about the .htaccess.default file has been removed.
- The reference about the [rewriteUrl](https://github.com/contao/core-bundle/blob/master/CHANGELOG.md#improved-1) option in the settings has been removed.
### Not ready
- The reference about the default demo template has been removed.
### Contao system requirements
- The minimum versions of PHP and MySQL have been increased.

### CODE REVIEW

**Comment by aschempp** [comment]
Looks very good to me! The Contao Association is pursuing a few ideas about the Contao demo, so I'm totally fine with removing that section for now.

I think this is all good for translation :-)

**Comment by lionel-m** [comment]
It's done thx

**Comment by aschempp** [comment]
Be aware that I reverted two changes: https://github.com/contao/docs/commit/73a7451d87a42a3367a57112bf95b76168e7cab4#diff-d67255ae092bca155c31044c8dacac5aR71

I doubt the closing elements will get a CSS class, as they're only closing `</div>` tags or similar, right?

**Comment by lionel-m** [comment]
Yes, it is because I changed it based on this [list](https://github.com/contao/core-bundle/blob/master/UPGRADE.md#template-name-changes). I will modify the French version accordingly.

**Comment by aschempp** [comment]
Well the template names have changed, but there is no such CSS class

**Pull request merged**
