### PR TITLE
Chapter 1 : Update "contao-check.jpg"

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
Why did you change the file name?

**Comment by lionel-m** [comment]
The image in English has the same name. Simply to differentiate from it.

**Comment by aschempp** [comment]
But they are in differnet folders? And it was not different before? Maybe I'm overseeing something?

**Comment by lionel-m** [comment]
I will remove the "-de". This is not a problem...

> And it was not different before?

Very little. I had to create an image for the French version so I also updated in other languages.

**Comment by aschempp** [comment]
I did not mean the difference in the image ;-)
I meant the file name was without `-de` previously, so maybe I misunderstood why you added it? ;-)

**Comment by lionel-m** [comment]
I renamed the file as before.

**Comment by aschempp** [comment]
Merged in fdda7a9442ff7d221a2cd69ad0ace81435b28cea

**Pull request merged**
