### PR TITLE
Added Information about "TinyMCE anpassen" in Contao 4

### PR DESCRIPTION
**Pull request by christianromeni**
I wanted to add the chapter "7.4. TinyMCE anpassen" to the Contao 4 Docs, it took me some time to find out the template HAS to be in the root template folder and not in a subfolder.
Also I wanted to give the hint about the style_formats_merge: true line, since that is very handy!
I have only added it in german so far..

### CODE REVIEW

**Comment by lionel-m** [comment]
Thank you for your contribution @christianromeni !

The chapter about DCA is now [in the API](https://docs.contao.org/books/api/dca/index.html) and this part of the doc is available in English only.

The part about TinyMCE [is in the cookbook](https://docs.contao.org/books/cookbook/customizing-contao/customizing-tinymce.html) but I think it has its place in the manual. However, we should not create a new chapter just for this information. We have to decide where to place this new content in the existing chapters. @aschempp, what do you think ?

**Comment by christianromeni** [comment]
Ok, actually I added the DCA part only to make it have the same structure as the one from 3.4

As I see it, some parts change from version to version.
Like in this case, the template came in Contao 4. If its put in the cookbook, its not version specific.
So I would actually put it back in the manual.

Let me just know what to do.

**Comment by lionel-m** [comment]
> As I see it, some parts change from version to version.

Yes the structure of the version 3.5 is now the reference.

>  If its put in the cookbook, its not version specific.

This is something we must resolve in the future...

I'm for adding this information in the manual. Probably in the chapter 04 "managing-content" (what do you think?) but before I would like to know the opinion of @aschempp.

**Comment by aschempp** [comment]
I think the cookbook chapter is correct for this topic, as the content explains a one-off topic not related to anything else in the manual. It is similar to a wiki article about exactly one topic. The Contao 3 vs. Contao 4 issue can easily be solved be either creating two cookbook entries or have two parts in the cookbook.

**Comment by lionel-m** [comment]
> The Contao 3 vs. Contao 4 issue can easily be solved be either creating two cookbook entries or have two parts in the cookbook.

I prefer two parts:

```
Contao 3
  1 Deutsch
     1.1 Inhaltselemente verwenden
     1.2 ...
  2 English
     2.1 Using content elements
     2.2 ...
Contao 4
  1 Customizing TinyMCE 
  2 ...
  3 ...
```

We can add [headings in the summary](https://github.com/GitbookIO/gitbook/blob/master/docs/pages.md#parts)

**Comment by aschempp** [comment]
That's probably not best, because almost all cookbook articles for Contao 3 also apply to Contao 4 (as the API is backwards compatible)…

**Comment by lionel-m** [comment]
Yes right...

So as you said [in this comment](https://github.com/contao/docs/issues/378#issuecomment-222070611), the tag is globally the most suitable solution 👍 .

**Comment by lionel-m** [comment]
@christianromeni Could you add your contribution in the cookbook please. So far as possible we would like to have the cookbook in English only so could you also translate your text if possible?

@aschempp, @christianromeni We have already [a chapter](https://docs.contao.org/books/cookbook/customizing-contao/customizing-tinymce.html) that addresses this subject for Contao 3.x. So this text could be added below and we can identify the version with the following code `> **Tag** The text below concerns the version 4.0.0 and higher.` (Something like that...).

**Comment by christianromeni** [comment]
Yes, I'll translate and add it to the cook book.. give me a few days.. currently a bit too busy...

**Comment by lionel-m** [comment]
Thanks 👍

**Comment by aschempp** [comment]
_ping_

**Comment by christianromeni** [comment]
Hab jetzt einen weiteren PR gemacht: #402

**Comment by aschempp** [comment]
Closed in favor of #402

**Pull request closed without merging**
