### PR TITLE
ATX style headers

### PR DESCRIPTION
**Pull request by fiedsch**
Changed headlines and added a `## More Information` section header
before `### References` and `### See Also`

### CODE REVIEW

**Comment by aschempp** [comment]
Great! But looks like the new hook descriptions also got pushed? Was that intended?

**Comment by fiedsch** [comment]
> Was that intended?

No. I created a new branch and thought that would solve that problem. Put probably the unchanged files got "touched" (got a new timestamp) anyway. 

What can I do about that?

**Comment by aschempp** [comment]
well not really much, but I can cherry-pick the changes if you think it's ready to be merged (looks good to me).

**Comment by fiedsch** [comment]
I made a diff against the old files and saw the changes as intended. So yes, I think they are ready.

**Comment by aschempp** [comment]
Cherry-picked in 2abb705ce0b5e6305ad6cf4d55def45512b146f7

**Pull request closed without merging**
