### PR TITLE
update min PHP version

### PR DESCRIPTION
**Pull request by fritzmg**
Contao `4.4.x`  requires PHP `5.6`.

### CODE REVIEW

**Comment by aschempp** [comment]
merged in 73ba953

**Comment by binarious** [comment]
Just a little reminder: It's still showing 5.5.

**Comment by xchs** [comment]
> Just a little reminder: It's still showing 5.5.

It was merged into the `4.4` branch. On docs.contao.org the last user manual refers to Contao 4.3.

**Comment by binarious** [comment]
Right. Should be updated, I think. When you browse to https://contao.org/en/download.html you'll get 4.4.3. When you scroll down to _System requirements_ and click on the link, you see PHP 5.5 (because the docs are still on 4.3) which is wrong.

**Comment by fritzmg** [comment]
Indeed. The documentation for 4.4 needs to be released on docs.contao.org

**Comment by aschempp** [comment]
Finally done 😓

**Pull request closed without merging**
