### PR TITLE
Update the example code for the data container configuration

### PR DESCRIPTION
**Pull request by xchs**
- _"Customizing Contao"_ > _"Customizing the data container configuration"_
- Change the given example code to comply with the new static methods

### CODE REVIEW

**Comment by aschempp** [comment]
I like the change. However, we currently do not recommend this anywhere. Should we update the documentation everywhere the user object is used? And for 3.x only, or also for Contao 2.11?

**Comment by xchs** [comment]
Leo thinks about postponing the changes regarding the static methods and to continue to load the files in an object context (see https://github.com/contao/core/issues/5387#issuecomment-13945896). So, for the moment, we maybe should stick with the current version until a definite decision was taken.

**Comment by leofeyer** [comment]
However, the new version does work in Contao 2 and Contao 3 and will not require adjustment in Contao 4, so I think its not too bad an idea to recommend it :)

**Comment by aschempp** [comment]
I have merged your pull request and updated all other related files in Contao 2.11 and 3.0 documentation.

**Comment by xchs** [comment]
Thank you.

**Pull request merged**
