### PR TITLE
Update 07-Customizing-Contao.md

### PR DESCRIPTION
**Pull request by Aybee**
Based on Contao 3.2.7

Removed Hooks:
1. loadFormField
2. processFormData
3. validateFormField

Added Hooks:
1. generateXmlFiles
2. getArticle
3. getAttributesFromDca
4. getCacheKey
5. getCombinedFile
6. getCountries
7. getForm
8. getFrontendModule
9. getRootPageFromUrl
10. getSystemMessages
11. getUserNavigation
12. indexPage
13. insertTagFlags
14. isAllowedToEditComment
15. isVisibleElement
16. modifyFrontendPage
17. parseArticles
18. parseTemplate
19. parseWidget
20. replaceDynamicScriptTags
21. setCookie
22. sqlCompileCommands
23. sqlGetFromDB
24. sqlGetFromDca
25. sqlGetFromFile
26. updatePersonalData

Some alphabetic sorting

### CODE REVIEW

**Comment by aschempp** [comment]
I have started documenting hooks in https://github.com/contao/docs/blob/3.2/api/hooks.md a while ago, not sure if you seen that? It would however likely make sense to include your work in the manual, because I don't know when the new stuff will be released.

Also, why did you remove the three hooks? As far as I know, they are still valid in Contao 3.2?

**Comment by Aybee** [comment]
No, I didn't know about that. Perhaps you can put a link into the manual.

I searched the core for those three removed hooks and could not find them.

Yes, I think it will make sence to merge the request even if the new hooks aren't commented yet. Maybe you or someone else can finish it.

I have an .ods file with comparison of the hooks in manual 3.2 and Contao 3.2.7 tell me, if you need it.

**Comment by Aybee** [comment]
Ups, das ist ja tödlich, mein neues Win7 hat irgendwie die Form.php eliminiert. Jetzt sind die 3 von mir gelöschten HOOKS auch wieder da.

I will send you a new pull request containing the 3 removed HOOKS, sorry for that.

**Comment by aschempp** [comment]
Ein neuer Pull-Request ist nicht nötig, die Änderungen im selben Branch erscheinen ja hier ;-)

**Comment by Aybee** [comment]
Ach so ist das ;) danke.

**Comment by aschempp** [comment]
Mittlerweile haben wir das neue API-Handbuch veröffentlicht: https://docs.contao.org/books/api/extensions/hooks/index.html

Praktisch alle Hooks sind dort bereits schon vorhanden, ich schliesse deshalb diesen PR. Sehr gerne natürlich PRs für die noch fehlenden Hooks ;-)

**Pull request closed without merging**
