### PR TITLE
Insert tags improvements

### PR DESCRIPTION
**Pull request by lionel-m**
What's your opinion please?

### CODE REVIEW

**Comment by aschempp** [comment]
Well the list of options is not really defined, as it can load any language strings. The ones you mentioned are just the known codes for certain things (e.g. for countries). But you can also use `MSC` or `ERR` from the `default.php`.

I don't know if people really need `MOD` for example? Or maybe we should only tell about the "useful" codes?

**Comment by lionel-m** [comment]
> Or maybe we should only tell about the "useful" codes?

Yes I will make some changes.

**Comment by lionel-m** [comment]
Now there are just two examples to explain we can use acronyms too.

**Comment by aschempp** [comment]
I like that :-)
Will you add the other translations?

**Comment by lionel-m** [comment]
It's ok to merge. French translation added.

**Comment by aschempp** [comment]
Merged in 077f97ba6f21dd484b16a865fdecacc1662183ae

**Pull request merged**
