### PR TITLE
Improvements and fixes after the PR #234

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by lionel-m** [comment]
I stop the modifications for this PR. I'll check my [last commit](https://github.com/lionel-m/docs/commit/7f116f4a43994b7bad23e310e6ce4d0090f42495) about the wrong relative paths online and if this is correct, I will do the changes for other languages.

**Comment by aschempp** [comment]
Changes are merged!

Be aware that you can also use string aliases instead of numeric ones for the links. Anything within square brackets is valid. Might be a bit easier ;-)

**Comment by lionel-m** [comment]
Thanks ! Could you add these modifications online for testing purpose ? Is it automatic ?

> Be aware that you can also use string aliases instead of numeric ones for the links.

Personally I prefer to use numeric values :)

**Comment by aschempp** [comment]
The changes are compiled automatically (if successful, see https://travis-ci.org/contao/docs/builds). You can find it at https://docs.contao.org/books/manual/3.2/ for example.

**Pull request merged**
