### PR TITLE
Fix getCountries

### PR DESCRIPTION
**Pull request by fiedsch**
add reference and remove unnecessary return value. See
https://github.com/contao/core/issues/8106#issuecomment-156441813

### CODE REVIEW

**Comment by aschempp** [comment]
Thanks for the fix. Reading through [the code](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/System.php#L381-L412) it does not really make sense to me to change the second variable at all? It is not used. Also, I would rename the `$return` value.

Basically, the first argument to the hook is the translated & returned countries, the second one is the original values, though I can't think of any use case for that variable…

**Comment by fiedsch** [comment]
Well, I did not really think about this. While leaving the original examples as they were I just added the reference and removed the return value that would cause no error but is useless as it is not used anywhere.

I don't know who originally created the examples, but I guess `$arrReturn` got it's name because the value passed in is called $return in the calling code. (Btw. I would prefer something like `return $result` there -- but that's not the point here).

I'll update my PR and remove the second example. If someone can show why it would make sense we can easily add it again.

Concerning the parameter names -- how about 

``` php
public function myGetCountries(&$arrCountriesList, $arrCountriesConfig)
```

and then (in the parameters description above) 

"Empty array that should be used to add custom entries."

(which is wrong because it is not empty) replaced by

"The array containing the countries as filled by `\System::getCountries()` according to the system's configuration. This parameter has to be passed by reference."

Just out of curiosity: why do we have hooks where parameters have to be passed by reference and others that follow this pattern:

``` php
$value = someFunction(..., $value, ...);
```

I don't get the point.

**Comment by fiedsch** [comment]
Updated my PR

**Comment by aschempp** [comment]
Much better!

A few suggestions:
- Call the variables `$translatedCountries` and `$allCountries`. We don't prefix variables anymore since Contao 4.
- The first parameter is the list of translated countries, the second one is the original list from system configuration (english). None of them must be passed by reference, but if not then one can't modify it ;-)
- The example is very good, but it should be valid PHP (move `…` into a comment block)

**Comment by bekanntmacher** [comment]
Danke für die Nachricht,
wir sind ab dem 23. November gerne wieder für Sie da!

E-Mails werden nicht weitergeleitet. Unsere Geschäftsnummer 071 222 90 10 bleibt aber während dieser Zeit bedient. 

Herbstgrüsse vom Team bekanntmacher
...
bekanntmacher, Schokoladenweg 10, 9011 St. Gallen 
T 071 222 90 10, http://www.bekanntmacher.ch

**Comment by fiedsch** [comment]
Thanks for your feedback. I'll update the PR this evening when I'm at home.

> We don't prefix variables anymore since Contao 4.

very nice -- never really got used to that

**Comment by fiedsch** [comment]
updated my PR as proposed

**Comment by aschempp** [comment]
Thanks!

**Pull request merged**
