### PR TITLE
Update information about the browsers compatibility

### PR DESCRIPTION
**Pull request by lionel-m**
The reference "from version 2" is too old (2006) to be helpful so I remove it. This is from version 9 for IE. Correct?

Related to #350

### CODE REVIEW

**Comment by aschempp** [comment]
Looks valid. Can you add french and german?

**Comment by lionel-m** [comment]
It's done

**Comment by aschempp** [comment]
I think this should be applied to the 3.5 manual as well, right?

**Comment by lionel-m** [comment]
> I think this should be applied to the 3.5 manual as well, right?

I don't know...

I created a new PR #440 if needed.

**Comment by aschempp** [comment]
Closed in favor of #440

**Pull request closed without merging**
