### PR TITLE
Small correction to the getFrontendModule hook documentation

### PR DESCRIPTION
**Pull request by koertho**
Added changes introduced with 3.0, added contao 4.4 reference

### CODE REVIEW

**Comment by aschempp** [comment]
thanks! Was the frontend module added in Contao 4? I think we should add a respective hint to the argument instead of a generic "updated" information.

**Comment by koertho** [comment]
No, it was added in Contao 3. But thats a good idea, I just didn't found a already documented change, so I didn't had a template for orientation.

**Comment by koertho** [comment]
I've added a changelog instead a direct hint at the parameter, like it is done in the PHP documentation. I think this is the best solution.

**Comment by aschempp** [comment]
Very good idea, thank you!

**Pull request merged**
