### PR TITLE
Fix/contao installation

### PR DESCRIPTION
**Pull request by Zeromax**
Add an Administraion Hint for Windows.
Symlink creation under windows is only possible as Admin.

### CODE REVIEW

**Comment by aschempp** [comment]
Would that mean only an administrator can install Contao on windows?

/cc @contao/developers

**Comment by Zeromax** [comment]
Yes. I do not know why this is the case on windows. It is only the symlink stuff which does only work, if you are an admin.

**Comment by leofeyer** [comment]
Nope, you are wrong. The tests on appveyor.com show that this is not a Windows issue but an XAMPP limitation (see my comments [here](https://github.com/contao/core-bundle/issues/208#issuecomment-138114929) and [here](https://github.com/contao/core-bundle/issues/208#issuecomment-138267806)).

**Comment by aschempp** [comment]
So should we update the note to tell about XAMPP on windows?

**Comment by Zeromax** [comment]
@leofeyer sorry I do not get what `PHP with FCGI` has to do with `PHP with CLI`. Except that both is PHP... Sure, it is possible that this is a XAMPP PHP limitation. But I don't think so.

Here I am talking about: `php composer.phar create-project contao/standard-edition:4.0.2 <target>`
This is a `CLI` command wich never triggers any `php_mod` or `fcgi mod`. It triggers PHP direct.
unbenannt

Or do I get something wrong in general?

Here is a cli output where I trigger the `mklink` on windows direct:
Left Normal User | on the right Admin User
unbenannt
You see: The symlink is not created by a normal user. (I am on Windows 10)

**Comment by aschempp** [comment]
How do we continue with this @leofeyer @Zeromax ?

**Comment by leofeyer** [comment]
I don't know. Obviously it is an XAMPP limitation that can be solved in two ways:
1. Run the Composer commands as administrator. Certainly an easy but also risky solution.
2. Replace the XAMPP built-in mod_php with [FastCGI](https://commaster.net/content/installing-php-fastcgi-and-zend-opcache-xampp-windows). More complex but does not require admin privileges. And it feels more like a real solution instead of just a workaround.

**Comment by aschempp** [comment]
Ok, so I would suggest to change the sentence to something like

> On Windows, depending on the setup (e.g. default XAMPP), you might need run this command as an administrator.

@lionel-m can you verify the french version?

**Comment by lionel-m** [comment]
> On Windows, depending on the setup (e.g. default XAMPP), you might need run this command as an administrator.

Sous Windows, en fonction de la configuration (par ex. XAMPP par défaut), vous devrez peut-être exécuter cette commande en tant qu'administrateur.

**Comment by aschempp** [comment]
@Zeromax can you update the pull request?

**Comment by aschempp** [comment]
Merged in bba870a

**Pull request closed without merging**
