### PR TITLE
Use example domain name (RFC2606).

### PR DESCRIPTION
**Pull request by taca**
Use reserved domain names (RFC2606).

I tried to fix English version only since I do not know such example domain names exists in ".de" domain.  (There are example domain names in "jp" domain.)

### CODE REVIEW

**Comment by aschempp** [comment]
Thanks! As fas as I know, there are no example domains for german. Could you update the german manual for `example.com` too?

**Comment by aschempp** [comment]
Thanks a lot! Merged in 6d4572106e663afdea9ef8b54ba3b3f0623781fc

@lionel-m you might want to apply this in the french documentation

**Comment by lionel-m** [comment]
Yep thanks.

There is "personal-website.com" in the first table... It should be replaced by "www.personal.example.org" ?

**Comment by taca** [comment]
Sure.  I've requested one more pull-up.

**Pull request merged**
