### PR TITLE
Some improvements to be compatible with the version 3

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
I think we should rename the second "Move" icon to "Drag & Drop". Can you update the image?
I'll add the german translation :-)

**Comment by lionel-m** [comment]
"Drag & drop" also for the image in German ?

**Comment by aschempp** [comment]
I think that is a common name, so I'm fine with it. @leofeyer ?

**Comment by aschempp** [comment]
@leofeyer any feedback?

**Comment by leofeyer** [comment]
The list view offers a "move" action?

"Drag und Drop" or "Drag & Drop" is fine in German. I prefer it over "Ziehen & Ablegen".

**Comment by aschempp** [comment]
True, the list view does not (yet) support "move".

**Comment by lionel-m** [comment]
I mixed up these two terms.

For example : https://contao.org/en/manual/3.1/administration-area.html#parent-view-icons

**Comment by lionel-m** [comment]
I will create a new pull request.

**Pull request closed without merging**
