### PR TITLE
Update readme file for Contao 3.4 only (French)

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
Merged in a786ec6c0bd567d07bbd280febcca2d584dd9888

Please be aware that I cannot merge 3 pull requests that contain almost the same information into three different branches. Each version has to be merged into the next one (e.g. 3.2 into 3.3, 3.3 into 3.4), and that would not work with your PR.
In this case, the PR for 3.3 would have been enough, as I would be able to remove the warning from 3.2 and 3.4 ;-)

**Comment by lionel-m** [comment]
Yes but the title also changes in each milestone and this is why I had to create 3 versions.
Now the title is wrong in 3.3 and 3.4.
Next time I create one version and specify the small changes to make.

**Comment by lionel-m** [comment]
Can you edit the titles without creating a PR?

**Comment by aschempp** [comment]
Sure :D

**Comment by lionel-m** [comment]
:+1:  Thanks

**Pull request closed without merging**
