### PR TITLE
Update images for the chapter 2 and 5

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by lionel-m** [comment]
PSD files available if needed.

Finished

**Comment by aschempp** [comment]
Great! I just noticed a little "issue". The screenshots seem to be from Contao 3.1. This especially affects the drag&drop handle. Also, is the "Generate aliases" button available in 3.0?

**Comment by qzminski** [comment]
The "Generate aliases" button is already available in 3.0.

**Comment by aschempp** [comment]
Hey, will you update the images? Or should I just merge it into 3.1 only?

**Comment by lionel-m** [comment]
You can merge it into 3.1 and I will do a new pull request for 3.0.

Thx

**Comment by aschempp** [comment]
Please also fix the notice from #37

**Comment by aschempp** [comment]
I have found a typing mistake on tree-view-icons-de.jpg. It should say _Dahinter einfügen_, _Dahunter_ is completely wrong ;-)

**Comment by lionel-m** [comment]
This issue is for the 3.1 branch. Sorry...
I have to recreate a new fork after my issues will be accepted

**Comment by lionel-m** [comment]
Revised

**Comment by aschempp** [comment]
Merged in bf019344fa86e740eccc608a04d0a4d27fbc855d

**Pull request closed without merging**
