### PR TITLE
Escape prefixes so that they are not considered by the Markdown language.

### PR DESCRIPTION
**Pull request by lionel-m**
....

### CODE REVIEW

**Comment by lionel-m** [comment]
Here was a problem that would have been difficult to find without Travis... Excellent solution :)

**Comment by lionel-m** [comment]
@aschempp : It does not work... An idea?

**Comment by aschempp** [comment]
You need to use two underscores for escaping (see 789b2e4bbf0d34eaa67c9f8d7203303fd8f7821d)

**Comment by lionel-m** [comment]
@aschempp : It still does not work... The double underscore are transformed by Markdown in bold.

https://docs.contao.org/books/manual/3.4/en/03-managing-pages/style-sheets.html

**Comment by aschempp** [comment]
A backslash does the trick (book is being built and will be online in a few minutes).

**Comment by lionel-m** [comment]
This is the solution! I will create a PR to fix the other languages too.

**Pull request merged**
