### PR TITLE
Added a PHP tag to enable the syntax highlighting scheme in code blocks

### PR DESCRIPTION
**Pull request by xchs**
- added a PHP tag to enable the syntax highlighting scheme in MD code blocks
- changed the formatting syntax of unordered lists and inline code, respectively
- removed some trailing whitespace characters

### CODE REVIEW

**Comment by aschempp** [comment]
Wow, thanks for the quick help! I didn't know about single backtick operator, that totally makes sense. However, I prefer to use hyphens for unordered lists, as asterisk also define formatting (bold/italic), and to me the list looks cleaner in raw text?

Regarding the opening <?php tag, I don't think it will be necessary.
1. the code highlighter is applied
2. wouldn't we need ending ?> then?
3. I imagine we will add more formatting to code blocks, like a headline that says it is PHP...

Can you update the pull request, or do you have feedback on my feedback? ;-)

**Comment by aschempp** [comment]
Ah, I just noticed we need the opening <?php tag to enable syntax highlight on GitHub. Nice catch, totally agree then. Can you please add an empty new line after that?

**Comment by xchs** [comment]
> Can you please add an empty new line after that?

Yes, of course.

> I prefer to use hyphens for unordered lists

I will change this, too. However, in the official [GitHub Flavored Markdown (GFM)](http://github.github.com/github-flavored-markdown/) syntax I find everywhere the asterisk symbol to format unordered list. Nonetheless, you were right: the (standard) [Markdown syntax guide](http://daringfireball.net/projects/markdown/syntax) quotes &ndash; additionally to the **asterisk** symbol &ndash; also **pluses** and **hyphens** as list markers for unordered (bulleted) lists. That was new for me, too.

**Comment by xchs** [comment]
Done. The new commit is 0a5318f8a3bb3e65f16f8b566e179cbca34d3858.

**Pull request merged**
