### PR TITLE
Chapter 8 (update)

### PR DESCRIPTION
**Pull request by lionel-m**
- Add new categories.
- Add GitHub import in the Extension Repository.
- Add new images (github-import.jpg + github-import-tag.jpg).
- Update images (add-extension.jpg + edit-files.jpg).

### CODE REVIEW

**Comment by lionel-m** [comment]
Issue #20

**Comment by lionel-m** [comment]
Another of my changes was added in this pull request.

Chapter 03 - Managing pages.
Reference : https://contao.org/en/manual/3.0/managing-pages.html#modules

**Comment by aschempp** [comment]
Just asking: do you speak german too? ;-)

**Comment by lionel-m** [comment]
Ich kann auch das Kapitel 3 ändern :)

**Comment by aschempp** [comment]
Es wäre natürlich perfekt, wenn du auch gleich die entsprechenden deutschen Versionen machen kannst?

**Comment by lionel-m** [comment]
Finished.

**Comment by leofeyer** [comment]
Merged in 17fd673f29ee51a9f8d9bab4f296822a7a06dce1. Thanks a lot for your help :)

**Pull request merged**
