### PR TITLE
Fix code highlighter for GitBook - PR 1/2

### PR DESCRIPTION
**Pull request by lionel-m**
This is the first PR from version 2.11.
I will create a second PR from version 3.2 (including French translation, contributing.md)

### CODE REVIEW

**Comment by lionel-m** [comment]
Related to #228

**Comment by lionel-m** [comment]
@aschempp Could you merge this PR before I created the second? Thanks

**Comment by aschempp** [comment]
We are not maintaining the 2.11 version anymore, that's why I wrote

> Please change all appearances including the CONTRIBUTING.md **in the 3.2 branch**

;-)

I have cherry-picked your changes into the 3.2 branch in 68a4da2c768024ed3e2c1f35a683d816d21ace00, but please verify 3.2 again and create a new PR for the french version and anything missed.

**Comment by lionel-m** [comment]
> We are not maintaining the 2.11 version anymore

The manual version 2.11 is available in the new website. I would like to know which manual will be visible at the end... And for 3.0 and 3.1?

I will make a second PR.

**Comment by aschempp** [comment]
All versions will be visible on the new website, but we should not put efforts into them. They work as they are, they're just not as nice as the maintained version.

**Pull request closed without merging**
