### PR TITLE
Remove "tableless" info because all forms are now tableless by default

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
Shouldn't you adjust all languages? Or at least french, too? ;-)

**Comment by lionel-m** [comment]
If you agree, I propose the changes only in English and if the PR is validated, I make the translation into French then... This PR is not a good example ;) but when there are a lot of changes or new contents this avoids having to change the translation too.

**Comment by aschempp** [comment]
Sure thing, that's fine with me. Would you want me to merge the english changes only or just approve them so you can add the others to the same PR?

**Comment by lionel-m** [comment]
> ... or just approve them so you can add the others to the same PR?

Yes and in the same PR :)

**Pull request merged**
