### PR TITLE
added example to fields at labels

### PR DESCRIPTION
**Pull request by iCodr8**

### CODE REVIEW

**Comment by aschempp** [comment]
What is the colon part for? @leofeyer

**Comment by iCodr8** [comment]
I found it here https://github.com/contao/core/issues/88#issuecomment-2931656 and I knew that never. So I thought this would be helpful in the documentation.

**Comment by aschempp** [comment]
Good catch! Did you actually use it in the latest Contao version?

**Comment by iCodr8** [comment]
Yes 3.2.4, I am working very often with foreignKeys in Contao.

**Comment by Toflar** [comment]
Oh, I did not know that either :D But if I did not know the code now I would still have trouble understanding what it does. Can you maybe add a little more explanation on this feature? That would be awesome!

**Comment by aschempp** [comment]
Merged in f3546c3911e2419fb273aeef309598c57bd77394

**Pull request closed without merging**
