### PR TITLE
add postAuthenticate hook

### LINKED ISSUE #284: [3.5] add postAuthenticate hook to api documentation

### PR DESCRIPTION
**Pull request by bezin**
Pickung up on this one after quite a long absence. fixes #284 

I also included a link to the github issue, since this hook was implemented after a community request. I added a discussion section at the end of the doc. Your comments are welcome.

### CODE REVIEW

**Comment by aschempp** [comment]
I like the discussion link, but it could as well go into the "See also" section, right? I would also call the link `contao/core#5864` so we know instantly which repo it is.

**Comment by bezin** [comment]
Thanks for your comment. I agree and fixed it.

**Comment by aschempp** [comment]
Thanks!

Two more adjustments neccessary:
1. please limit line length to 80 chars (see contribution guidelines)
2. Also add the new hook to the summary files

**Comment by fiedsch** [comment]
"User $objUser The user (object) which has been logged out." seems wrong for the postAuthenticate hook (maybe a leftover from postLogut?).

**Pull request merged**
