### PR TITLE
Update images for the chapter 2 and 5 (Contao 3.0)

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
I have found a typing mistake on `tree-view-icons-de.jpg`. It should say _Danach einfügen_, _Dahunter_ is completely wrong ;-)

**Comment by aschempp** [comment]
Doh. I should be _Darunter_ obviously!

**Comment by aschempp** [comment]
All other images are good!

**Comment by aschempp** [comment]
Closing this, its a duplicate of #29

**Comment by lionel-m** [comment]
This is not a duplicate. There are differences between the version 3.0 and 3.1

**Pull request closed without merging**
