### PR TITLE
Add template variables to cookbook

### PR DESCRIPTION
**Pull request by eknoes**
A short article about finding and using template variables for the contao cookbook.

### CODE REVIEW

**Comment by aschempp** [comment]
Thanks a lot! I really like the introduction! It has a few typos and the headlines are not semantic, but that should be an easy fix (I can do that if you're ok with that).

Regarding the second document, as explained in the forums I don't think it makes sense to describe individual variables. The ones you mentioned are likely only valid in a `ce_image` template and nowhere else. However, I like the point about unserialization, could we add that as a separate sectino into the main file?

**Comment by eknoes** [comment]
Yes, I just did not know where to write about the (un)serialization part, because I think thats pretty important. In the moment I am not so into php and I had to search a lot, until I did know that these are serialized arrays.

I will rewrite it in the next few days :)

**Comment by Toflar** [comment]
I didn't read it yet, I just wanted to jump in and say thank you for contributing!

**Comment by eknoes** [comment]
Hey, I just rewrote it and corrected spelling and grammar.

**Comment by aschempp** [comment]
Thanks! I did a few little adjustments according to our contribution guidelines in 4415ca9997e485930569e72a7d9a905f8d752882

**Pull request merged**
