### PR TITLE
Add documentation for the sysinit hook.

### PR DESCRIPTION
**Pull request by tristanlins**
See contao/core#5665

### CODE REVIEW

**Comment by tristanlins** [comment]
Name is up to date :-)

**Comment by aschempp** [comment]
Everyone be aware that we can't merge this on GitHub because it is on the wrong branch. Manual merging is "better" anyway :-)

**Comment by tristanlins** [comment]
But there is no 3.1 branch exists :D

**Comment by leofeyer** [comment]
True. I will create it in a minute :)

**Comment by leofeyer** [comment]
Done.

**Comment by tristanlins** [comment]
See the new PR

**Pull request closed without merging**
