### PR TITLE
Improve insert tag "file" with UUID #162

### PR DESCRIPTION
**Pull request by lionel-m**
Related to #162

### CODE REVIEW

**Comment by aschempp** [comment]
I assume this is for Contao 3.2 too (same as the french)? Just tell me I can still merge it ;-)

**Comment by lionel-m** [comment]
Yes sorry. I have to add the changes to the first branch. In this case 3.2

But for the French translation, it is only for version 3.2. I saw that you added the French translation in the 3.3 and 3.4 branches but I do not want to modify several versions for the French translation at the moment.

**Comment by lionel-m** [comment]
No it is for 3.2, 3.3 and 3.4.

Could you please remove the French translation in version 3.3 and 3.4 ? For example this modification https://github.com/contao/docs/pull/191 is not available in versions 3.3 and 3.4 and the translation is not up to date. It is better to keep only one version at the moment.

**Comment by aschempp** [comment]
I have merged it into 3.2 and later.

It is not possible to remove the french manual from 3.3 and 3.4. Whenever something is changed in 3.2, it will be merged in all later versions. The french version is identical in 3.2/3.3/3.4 though!

**Comment by lionel-m** [comment]
> Whenever something is changed in 3.2, it will be merged in all later versions. The french version is identical in 3.2/3.3/3.4 though!

Ah ok it's perfect in this case. Thanks for this info.

**Pull request closed without merging**
