### PR TITLE
Usernames and passwords are case-sensitive

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
This has been changed in Contao 3.1 right? @leofeyer

**Comment by leofeyer** [comment]
Actually, I am not quite sure about version 3.1. It has been changed in version 3.2.

**Comment by Toflar** [comment]
3.2 beta1 :) See https://contao.org/en/news/contao-3_2_beta1.html at the very bottom of the blog post :)

**Comment by aschempp** [comment]
Merged in 6c72f58fd17ffd9a64d30bf29ab498b5969670b2

**Pull request merged**
