### PR TITLE
Missing greater-than angle bracket

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
Nice catch!

I have added [a HTML5 validator](https://github.com/svenkreiss/html5validator) to check our books for any typing mistakes in the future. It actually leaded to [a fix in our book](https://github.com/contao/docs/commit/baac5fdea0dfa43d618b09a51c26f514ba4a56e5) as well as [several fixes to GitBook itself](https://github.com/GitbookIO/gitbook/pulls/aschempp) :-)

**Comment by lionel-m** [comment]
> I have added a HTML5 validator to check our books for any typing mistakes in the future.

Excellent idea :)

**Comment by aschempp** [comment]
It already leaded to some fixes :-)
https://github.com/contao/docs/commit/988f6f9a75d1af632bd7fac46c6cb98df869715b

**Comment by lionel-m** [comment]
Not easy to find this problem... :+1:

**Pull request merged**
