### PR TITLE
"Insert tag" in lowercase.

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by aschempp** [comment]
I think Insert Tag is meant to be a special word and therefore uppercase. @leofeyer maybe you remember the background, afaik you wrote the first manual?

**Comment by Toflar** [comment]
I'm with @aschempp . It's a **name** and thus should be uppercase but it's not handled equally throughout the manual nor the community :)

**Comment by lionel-m** [comment]
If it is considered as a proper noun, why not "Insert-Tag" with a dash between these two words ?

**Comment by NinaG** [comment]
+1 for Insert-Tag

**Comment by aschempp** [comment]
I like that idea. It could even be **InsertTag** to me as a _keyword_, because "insert tag" does not really describe something.

**Comment by Toflar** [comment]
Insert-Tag feels very German...I don't feel like an English native would add a dash in there.

**Comment by aschempp** [comment]
Maybe @BlairWinans can tell us?

**Comment by blairwinans** [comment]
InsertTag would be my choice, since we are using it as a specific noun/thing. I guess the argument could be made that with a dash, "Insert" becomes an adjective/modifier, making it a type of "Tag", but since "Insert" is a verb/action, it doesn't work as well.

**Comment by lionel-m** [comment]
@blairwinans Thanks. I modify with InsertTag if the others also agree.

**Comment by aschempp** [comment]
fine with me. Dunno if @leofeyer has an opinion :-)
If you find the time, it would be great if you adjust all languages of the manual.

**Comment by lionel-m** [comment]
> If you find the time, it would be great if you adjust all languages of the manual.

Yes

And in German there are "Inserttags" and "Insert-Tag"...

**Comment by lionel-m** [comment]
Do we use InsertTag as in English?

**Comment by aschempp** [comment]
I would, yes.

**Comment by Toflar** [comment]
I would use `InsertTag` in every language :)

**Comment by lionel-m** [comment]
@leofeyer Do you also accept this notation? `InsertTag`

**Comment by leofeyer** [comment]
No, it is actually "insert tag" in English and "Insert-Tag" in German.

**Comment by aschempp** [comment]
@leofeyer is this your opinion or is there an explanation why that's the case?

**Comment by leofeyer** [comment]
Well, "inserttag" is not an English word, therefore keep the two words separate.

In German its a bit more difficult since we are talking about an anglicism here. Generally there are three options:
1. Use the word as English word: "Insert Tag"
2. Use the word as compound word from the two English words: "Insert-Tag"
3. Create a new German word from the anglicism: "Inserttag"

When I was writing the Contao book, no. 2 was preferred by my editor.

**Comment by woerndl** [comment]
Full consent with @leofeyer's summary in https://github.com/contao/docs/pull/204#issuecomment-76154745. The seconds option is the only correct way to spell it (in German) as long as it is no registered trademark or similar.

**Comment by lionel-m** [comment]
We validate therefore :

In German : Insert-Tag
In English : Insert Tag

And always upper-case for both languages. Ok ?

**Comment by leofeyer** [comment]
No, it is "insert tag" in English, so the PR needs to be merged.

**Comment by lionel-m** [comment]
@leofeyer Thanks.

I will create a new PR

**Comment by aschempp** [comment]
Closed in favor of #385 and #386

**Pull request closed without merging**
