### PR TITLE
Update system requirements

### PR DESCRIPTION
**Pull request by lionel-m**

### CODE REVIEW

**Comment by lionel-m** [comment]
@aschempp : This has not been merged properly?

https://github.com/contao/docs/blob/3.4/manual/fr/01-Installation.md#configurations-du-syst%C3%A8me-requises-de-contao

**Comment by lionel-m** [comment]
Effectively : https://github.com/contao/docs/compare/d47c21832d...91f0dd007a
I create a new PR?

**Comment by aschempp** [comment]
A new PR would be great! I guess the problem happened because you changed the same file in 3 PRs ;-)

**Comment by aschempp** [comment]
Thanks anyways for checking!

**Pull request merged**
